# Generated by Django 3.0.6 on 2020-06-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=200)),
                ('project_url', models.CharField(max_length=200)),
            ],
        ),
    ]
