# Generated by Django 3.0.6 on 2020-05-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='name_here', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='project_url',
            field=models.CharField(default='link_here', max_length=200),
            preserve_default=False,
        ),
    ]
